---
- name: copy files
  hosts: kube
  become: true
  tasks: 
    - name: copy deployment file to kubernetes clusture
      copy: 
        src: dep.yml
        dest: .
    - name: create a Deployment
      command: kubectl apply -f /opt/dep.yml
...
