---
- hosts: kube
  become: true
    
    tasks:
     - name: copy deployment file to kubernetes clusture
     copy:
     src: dep.yml
     dest: /root
     - name: create a Deployment
       command: kubectl apply -f /root/dep.yml
...
