---
- name: copy files
  hosts: kube
  become: true
  tasks: 
    - name: copy deployment file to kubernetes clusture
      copy: 
        src: dep.yml
        dest: /home/centos
    - name: create a Deployment
      command: kubectl apply -f /home/centos/dep.yml
...
