---
- name: copy files
  hosts: kube
  tasks: 
    - name: copy deployment file to kubernetes clusture
      copy: 
        src: dep.yml
        dest: /home/centos
    - name: create a Deployment
      command: '/usr/local/bin/kubectl get all '
    - name: create a Deployment
      command: '/usr/local/bin/kubectl apply -f /home/centos/dep.yml'
...
