---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcal
  labels:
    app: webcal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webcal
  template:
    metadata:
      labels:
        app: webcal
    spec:
      containers:
      - name: webcal
        image: "nancy21/webcal"
        ports:
        - containerPort: 80
...


---
apiVersion: apps/v1
kind: Service
metadata:
  name: webcal-service
spec:
    app: webcal
    type: LoadBalancer
    ports:
        targetPort: 3000
        ports: 80
    selector:
        app: webcal	
...        
