---
apiVersion: v1
kind: Service
metadata:
  name: webcal-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3001
  selector:
    app: webcal
...


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcal
  labels:
    app: webcal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webcal
  template:
    metadata:
      labels:
        app: webcal
    spec:
      containers:
      - name: webcal
        image: "nancy21/webcal"
        ports:
        - containerPort: 80
...
