---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webappcal
  labels:
    app: webappcal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webappcal
  template:
    metadata:
      labels:
        app: webappcal
    spec:
      containers:
      - name: webappcal
        image: nancy21/proj
        ports:
        - containerPort: 80
...
